// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/type/matcher/v3/string.proto

package envoy_type_matcher_v3

import (
	fmt "fmt"
	_ "github.com/cilium/proxy/go/envoy/annotations"
	_ "github.com/cncf/udpa/go/udpa/annotations"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies the way to match a string.
// [#next-free-field: 6]
type StringMatcher struct {
	// Types that are valid to be assigned to MatchPattern:
	//	*StringMatcher_Exact
	//	*StringMatcher_Prefix
	//	*StringMatcher_Suffix
	//	*StringMatcher_SafeRegex
	MatchPattern         isStringMatcher_MatchPattern `protobuf_oneof:"match_pattern"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StringMatcher) Reset()         { *m = StringMatcher{} }
func (m *StringMatcher) String() string { return proto.CompactTextString(m) }
func (*StringMatcher) ProtoMessage()    {}
func (*StringMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_e33cffa01bf36e0e, []int{0}
}

func (m *StringMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMatcher.Unmarshal(m, b)
}
func (m *StringMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMatcher.Marshal(b, m, deterministic)
}
func (m *StringMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMatcher.Merge(m, src)
}
func (m *StringMatcher) XXX_Size() int {
	return xxx_messageInfo_StringMatcher.Size(m)
}
func (m *StringMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_StringMatcher proto.InternalMessageInfo

type isStringMatcher_MatchPattern interface {
	isStringMatcher_MatchPattern()
}

type StringMatcher_Exact struct {
	Exact string `protobuf:"bytes,1,opt,name=exact,proto3,oneof"`
}

type StringMatcher_Prefix struct {
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3,oneof"`
}

type StringMatcher_Suffix struct {
	Suffix string `protobuf:"bytes,3,opt,name=suffix,proto3,oneof"`
}

type StringMatcher_SafeRegex struct {
	SafeRegex *RegexMatcher `protobuf:"bytes,5,opt,name=safe_regex,json=safeRegex,proto3,oneof"`
}

func (*StringMatcher_Exact) isStringMatcher_MatchPattern() {}

func (*StringMatcher_Prefix) isStringMatcher_MatchPattern() {}

func (*StringMatcher_Suffix) isStringMatcher_MatchPattern() {}

func (*StringMatcher_SafeRegex) isStringMatcher_MatchPattern() {}

func (m *StringMatcher) GetMatchPattern() isStringMatcher_MatchPattern {
	if m != nil {
		return m.MatchPattern
	}
	return nil
}

func (m *StringMatcher) GetExact() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Exact); ok {
		return x.Exact
	}
	return ""
}

func (m *StringMatcher) GetPrefix() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Prefix); ok {
		return x.Prefix
	}
	return ""
}

func (m *StringMatcher) GetSuffix() string {
	if x, ok := m.GetMatchPattern().(*StringMatcher_Suffix); ok {
		return x.Suffix
	}
	return ""
}

func (m *StringMatcher) GetSafeRegex() *RegexMatcher {
	if x, ok := m.GetMatchPattern().(*StringMatcher_SafeRegex); ok {
		return x.SafeRegex
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StringMatcher) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StringMatcher_Exact)(nil),
		(*StringMatcher_Prefix)(nil),
		(*StringMatcher_Suffix)(nil),
		(*StringMatcher_SafeRegex)(nil),
	}
}

// Specifies a list of ways to match a string.
type ListStringMatcher struct {
	Patterns             []*StringMatcher `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListStringMatcher) Reset()         { *m = ListStringMatcher{} }
func (m *ListStringMatcher) String() string { return proto.CompactTextString(m) }
func (*ListStringMatcher) ProtoMessage()    {}
func (*ListStringMatcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_e33cffa01bf36e0e, []int{1}
}

func (m *ListStringMatcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStringMatcher.Unmarshal(m, b)
}
func (m *ListStringMatcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStringMatcher.Marshal(b, m, deterministic)
}
func (m *ListStringMatcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStringMatcher.Merge(m, src)
}
func (m *ListStringMatcher) XXX_Size() int {
	return xxx_messageInfo_ListStringMatcher.Size(m)
}
func (m *ListStringMatcher) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStringMatcher.DiscardUnknown(m)
}

var xxx_messageInfo_ListStringMatcher proto.InternalMessageInfo

func (m *ListStringMatcher) GetPatterns() []*StringMatcher {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func init() {
	proto.RegisterType((*StringMatcher)(nil), "envoy.type.matcher.v3.StringMatcher")
	proto.RegisterType((*ListStringMatcher)(nil), "envoy.type.matcher.v3.ListStringMatcher")
}

func init() { proto.RegisterFile("envoy/type/matcher/v3/string.proto", fileDescriptor_e33cffa01bf36e0e) }

var fileDescriptor_e33cffa01bf36e0e = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x6a, 0xf2, 0x30,
	0x18, 0xc6, 0x4d, 0xb5, 0x7e, 0x35, 0x22, 0xf8, 0x95, 0xef, 0x4f, 0xf1, 0x60, 0xd4, 0x2a, 0x9b,
	0x30, 0x68, 0x41, 0x77, 0xe4, 0x61, 0x8e, 0x44, 0xb6, 0x21, 0xdd, 0x05, 0x48, 0xa6, 0xd1, 0x15,
	0xb6, 0x26, 0x24, 0xb1, 0xd4, 0x3b, 0xd8, 0xc6, 0x8e, 0x76, 0xb8, 0xfb, 0xd9, 0x3d, 0x0d, 0x8f,
	0x46, 0x92, 0x4e, 0x26, 0x76, 0x67, 0x09, 0xcf, 0xef, 0x79, 0xde, 0x27, 0x79, 0x61, 0x40, 0xd2,
	0x8c, 0x6e, 0x23, 0xb9, 0x65, 0x24, 0x7a, 0xc0, 0x72, 0x71, 0x47, 0x78, 0x94, 0x8d, 0x22, 0x21,
	0x79, 0x92, 0xae, 0x43, 0xc6, 0xa9, 0xa4, 0xee, 0x5f, 0xcd, 0x84, 0x8a, 0x09, 0x0b, 0x26, 0xcc,
	0x46, 0x9d, 0x6e, 0xb9, 0x95, 0x93, 0x35, 0xc9, 0x8d, 0xb3, 0xd3, 0xdd, 0x2c, 0x19, 0x8e, 0x70,
	0x9a, 0x52, 0x89, 0x65, 0x42, 0x53, 0x11, 0x65, 0x84, 0x8b, 0x84, 0xa6, 0xfb, 0xf0, 0x4e, 0xcf,
	0xa4, 0x7c, 0x67, 0x96, 0x84, 0x71, 0xb2, 0xd0, 0x97, 0x02, 0xfa, 0x9f, 0xe1, 0xfb, 0x64, 0x89,
	0x25, 0x89, 0xbe, 0x0e, 0x46, 0x08, 0x9e, 0x2c, 0xd8, 0xba, 0xd1, 0x5d, 0xaf, 0x4c, 0x03, 0xf7,
	0x1f, 0xb4, 0x49, 0x8e, 0x17, 0xd2, 0x03, 0x3e, 0x18, 0x34, 0x26, 0x95, 0xd8, 0x5c, 0xdd, 0x2e,
	0xac, 0x33, 0x4e, 0x56, 0x49, 0xee, 0x59, 0x4a, 0x40, 0xbf, 0x76, 0xa8, 0xc6, 0x2d, 0x1f, 0x4c,
	0x2a, 0x71, 0x21, 0x28, 0x44, 0x6c, 0x56, 0x0a, 0xa9, 0x1e, 0x21, 0x46, 0x70, 0xaf, 0x21, 0x14,
	0x78, 0x45, 0xe6, 0xfa, 0x91, 0x9e, 0xed, 0x83, 0x41, 0x73, 0xd8, 0x0b, 0x4b, 0xff, 0x27, 0x8c,
	0x15, 0x53, 0xd4, 0x42, 0xce, 0x0e, 0xd9, 0xcf, 0xc0, 0x6a, 0xab, 0xb0, 0x86, 0x8a, 0xd0, 0xea,
	0xf8, 0xec, 0xed, 0xfd, 0xf1, 0x24, 0x80, 0x7e, 0x49, 0xc2, 0xc1, 0xb3, 0xd0, 0x1f, 0xd8, 0xd2,
	0xc2, 0x9c, 0x61, 0x29, 0x09, 0x4f, 0xdd, 0xea, 0x07, 0x02, 0xd3, 0x9a, 0x53, 0x6b, 0xdb, 0xb1,
	0xad, 0xdb, 0x04, 0x2f, 0x00, 0xfe, 0xbe, 0x4c, 0x84, 0x3c, 0xfc, 0x8f, 0x29, 0x74, 0x0a, 0x8b,
	0xf0, 0x80, 0x5f, 0x1d, 0x34, 0x87, 0xfd, 0x1f, 0xfa, 0x1e, 0x0e, 0x54, 0x85, 0x5f, 0x81, 0xe5,
	0x80, 0x78, 0xef, 0x1f, 0x9f, 0xab, 0xb6, 0xa7, 0xb0, 0x5f, 0xe2, 0x3f, 0x1a, 0x8c, 0x2e, 0x60,
	0x2f, 0xa1, 0x66, 0x14, 0xe3, 0x34, 0xdf, 0x96, 0x4f, 0x45, 0x4d, 0xe3, 0x9a, 0xa9, 0x75, 0xce,
	0xc0, 0x6d, 0x5d, 0xef, 0x75, 0xf4, 0x19, 0x00, 0x00, 0xff, 0xff, 0x90, 0xa1, 0x49, 0xcb, 0x98,
	0x02, 0x00, 0x00,
}
